import = ["/home/altair/.config/alacritty/dracula.toml"]

[cursor]
style = { shape="Beam", blinking="On" }
unfocused_hollow = true
#blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.bold]
family = "MesloLGSNerdFont"
style = "Bold"

[font.bold_italic]
family = "MesloLGSNerdFont"
style = "BoldItalic"

[font.italic]
family = "MesloLGSNerdFont"
style = "Italic"

[font.normal]
family = "MesloLGSNerdFont"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
opacity = 1
